// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	ValidateTokenUser(ctx context.Context, in *ValidateTokenRequestUser, opts ...grpc.CallOption) (*ValidateTokenResponseUser, error)
	ValidateTokenAdmin(ctx context.Context, in *ValidateTokenRequestAdmin, opts ...grpc.CallOption) (*ValidateTokenResponseAdmin, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ValidateTokenUser(ctx context.Context, in *ValidateTokenRequestUser, opts ...grpc.CallOption) (*ValidateTokenResponseUser, error) {
	out := new(ValidateTokenResponseUser)
	err := c.cc.Invoke(ctx, "/auth.AuthService/ValidateTokenUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateTokenAdmin(ctx context.Context, in *ValidateTokenRequestAdmin, opts ...grpc.CallOption) (*ValidateTokenResponseAdmin, error) {
	out := new(ValidateTokenResponseAdmin)
	err := c.cc.Invoke(ctx, "/auth.AuthService/ValidateTokenAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	ValidateTokenUser(context.Context, *ValidateTokenRequestUser) (*ValidateTokenResponseUser, error)
	ValidateTokenAdmin(context.Context, *ValidateTokenRequestAdmin) (*ValidateTokenResponseAdmin, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) ValidateTokenUser(context.Context, *ValidateTokenRequestUser) (*ValidateTokenResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTokenUser not implemented")
}
func (UnimplementedAuthServiceServer) ValidateTokenAdmin(context.Context, *ValidateTokenRequestAdmin) (*ValidateTokenResponseAdmin, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTokenAdmin not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_ValidateTokenUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequestUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateTokenUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/ValidateTokenUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateTokenUser(ctx, req.(*ValidateTokenRequestUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ValidateTokenAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequestAdmin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ValidateTokenAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthService/ValidateTokenAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ValidateTokenAdmin(ctx, req.(*ValidateTokenRequestAdmin))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateTokenUser",
			Handler:    _AuthService_ValidateTokenUser_Handler,
		},
		{
			MethodName: "ValidateTokenAdmin",
			Handler:    _AuthService_ValidateTokenAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
